/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppButton {
        "iconPath": string;
        "text": string;
    }
    interface AppHeader {
    }
}
export interface AppButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAppButtonElement;
}
declare global {
    interface HTMLAppButtonElement extends Components.AppButton, HTMLStencilElement {
    }
    var HTMLAppButtonElement: {
        prototype: HTMLAppButtonElement;
        new (): HTMLAppButtonElement;
    };
    interface HTMLAppHeaderElement extends Components.AppHeader, HTMLStencilElement {
    }
    var HTMLAppHeaderElement: {
        prototype: HTMLAppHeaderElement;
        new (): HTMLAppHeaderElement;
    };
    interface HTMLElementTagNameMap {
        "app-button": HTMLAppButtonElement;
        "app-header": HTMLAppHeaderElement;
    }
}
declare namespace LocalJSX {
    interface AppButton {
        "iconPath"?: string;
        "onLoginClicked"?: (event: AppButtonCustomEvent<void>) => void;
        "text"?: string;
    }
    interface AppHeader {
    }
    interface IntrinsicElements {
        "app-button": AppButton;
        "app-header": AppHeader;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-button": LocalJSX.AppButton & JSXBase.HTMLAttributes<HTMLAppButtonElement>;
            "app-header": LocalJSX.AppHeader & JSXBase.HTMLAttributes<HTMLAppHeaderElement>;
        }
    }
}
